### ISSUE TITLE
Its not working for wkhtmltopdf 

### ISSUE THREAD

**Issue by ashu-daffodil** [peterkeen/heroku-buildpack-vendorbinaries#4]
-----> Fetching custom git buildpack... done
-----> Multipack app detected
=====> Downloading Buildpack: https://github.com/ashu-daffodil/heroku-buildpack-vendorbinaries.git
=====> Detected Framework: VendorBinaries
-----> Found a .vendor_urls file
       Vendoring https://github.com/ashu-daffodil/HerokuTest1/blob/master/wkhtmltox.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Exiting with failure status due to previous errors

**Comment by peterkeen** [comment]
File doesn't exist any more so I can't do any testing. The most recently merged pull request may fix this?
